language: generic
dist: xenial
os: linux

services:
    - docker

before_install:
    - sudo apt-get install jq
    - curl -L https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 > yq && chmod +x yq && sudo cp yq /usr/bin/
    - sudo apt-get remove python3-pip
    - sudo apt-get install python3-pip python3-setuptools python3-wheel
    - sudo pip3 install -U setuptools
    - pip3 install --user --upgrade awscli
    - pip3 install --user --upgrade awsebcli
    - eb --version

    - pip3 install jsonschema==3.0.2

    - touch .env
    - rm docker-compose.yml
    - mv docker-travis.yml docker-compose.yml
    - ./deploy/scripts/travis_decrypt.sh

before_script:
    - ./deploy/scripts/travis_build.sh

script:
    - ./deploy/scripts/travis_test.sh

after_success:
    - ./deploy/scripts/travis_deploy.sh

notifications:
  slack:
    rooms:
      - secure: "fO3KT/4ejMvCfTfhrtJUcwt5m+f7P0vq1Zp12u4UAPVdcLouFIHQ9eSVnUO1KoHyplnH8kmvuJ7f9+XZcBgfYW3uBDFE40cwzJBzgVunyPrTJIqRlODaPcmS7YzWqcvuho/EN7XXn8mn2+76IS8ahgo235GsW6YBYuSxZpBTSLsc6j/jpCiLQ6nMTM6M/20L2eVfC2Sw/7yaIZNIJA0ZDVF5NDehAsPqqr9mvRjKqsRc44F1GTT11pDRIsjOA9K0SsvLICUc8PJ3wYbjrSNPuMyz7BZKozP0B5Wr2/DsRWq4dApqtkvnyc7j0E9o0bNpoAa99d1Gw/6FiDdfXoxXLyktEcVILwO4vXK2JfX1SOVrBXO/awVhfEJqfSEWgrjkFhKTnT73WoYLnTGkeHgBU3s2nYNOCvdPy+kDCo/lkC0RRWCcjxVzvt1wFjGWGWZ4itt89GBwekjYeNf1aZNxCDDo30fKa2cm9BkwIO2xhaQGa9QhXucptlNuJHu48g236pu2Iu5Lok8g/YckvKmKJrLGqVtLRKwMaR+hfsiuc5HoDZAgms1/I38nhqI5QxDLQmPl+hrQtAIJ10GBpBP2PX+V7yFqhUw3H0nT6iBKjCFYKwBFBecOdqWZznec5l8VVzIN2Yl+llD0ygtFXGOTa4fPE6c+0nxBIc2a8lLLfPU="
